language: go

sudo: false

go:
  - 1.5.x
  - 1.6.x
  - 1.7.x
  - master

before_install:
  - go get -u github.com/WindomZ/go-commander
  - go get -u github.com/WindomZ/testify/assert

script:
  - go test -v ./...
